#! /bin/bash

set -e
#set -x

S3MNT=$HOME/mnt2

STARTDIR=$PWD
REPO=$STARTDIR/map.git
UTILS=$STARTDIR/utils
TRACKER="http://bt.aux-cache.dev:9996/announce"

subd () {
	local d="$1"
	local f="$2"
	local sub=$(echo "$f" | cut -c 1-1)
	mkdir -p "${d}/${sub}"
	echo "${d}/${sub}/${f}"
}

closuref="$1"; shift
if [ -z "$closuref" ]; then
	echo "Usage: gen-torrents <closure-file>\n"
	exit 1
fi

cat $closuref | \
	sed -e 's|^/nix/store/||' \
		 -e 's/-.*$//' \
	| \
(while read; do
	echo $REPLY	
	tmpd=`mktemp -d`
	mkdir $tmpd/nix
	cd $tmpd/nix
	echo $tmpd
	inff=${REPLY}.narinfo
	ln -s $S3MNT/$inff .
	nar=$(grep ^URL: $inff | awk '{print $2}')
	mkdir nar
	ln -s $S3MNT/$nar nar
	cd ..
	cp -av $S3MNT/$inff $(subd $REPO $inff)
	torrentf=$(subd $REPO $REPLY.torrent)
	transmission-create -t "$TRACKER" -o "$torrentf" nix
	<$torrentf $UTILS/b2j.py | jq >${torrentf}.json
	cd /
	rm $tmpd/nix/nar/* $tmpd/nix/*.narinfo
	rmdir $tmpd/nix/nar $tmpd/nix $tmpd
done)


#for f in $(find map.git -name '*.torrent'); do cat $f | ./b2j.py >$f.json; done
